[package]
name = "monmouth-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "System utilities for Monmouth"

[lints]
workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
